RSDK-6122: getAccuracy
viamrobotics/viam-flutter-sdk pull request #170
Opened 2024-01-17 19:58 UTC by susmitaSanyal

Updating getAccuracy return type. 

Scope doc: [here](https://docs.google.com/document/d/1dbVI9njfMWXWg8B_wfRU9vCzi6pGQsgdwgqqjMB-Uhc/edit#heading=h.tcicyojyqi6c)

2024-01-22 22:22 UTC, susmitaSanyal commented
@benjirewis & @stuqdog , PR is ready for review. Let me know if I'm missing anything here.

2024-01-22 22:24 UTC, benjirewis commented
Ooh sorry missed this; I feel like I'm not really qualified to be reviewing these flutter PRs 😢 , gonna tag in @njooma.

2024-01-22 22:27 UTC, njooma requested changes

2024-01-22 22:27 UTC, njooma commented on lib/src/components/movement_sensor/movement_sensor.dart
> +}
Similar to python, this should be a typealias. You can basically copy the [next line](https://github.com/viamrobotics/viam-flutter-sdk/pull/170/files#diff-9829cc355197d082e394a03aab4e61e2f8e3397abff5c1c4e00f60c67f45debfL13) for example

2024-01-23 15:58 UTC, njooma commented on lib/src/components/movement_sensor/service.dart
> +    return GetAccuracyResponse(accuracy: accuracyM.accuracy)
I think you should just be able to `return await movementSensor.accuracy(...)` here

2024-01-23 16:38 UTC, njooma approved these changes

2024-01-23 16:39 UTC, merged