RSDK-7445: paginate data by filter methods
viamrobotics/viam-flutter-sdk pull request #213
Opened 2024-05-15 19:03 UTC by purplenicole730

2024-05-15 19:06 UTC, purplenicole730 commented on lib/src/app/data.dart
> +
I saw online that it was standard in Dart to make a class instead of returning a tuple. Let me know if this isn't what I should do.

2024-05-16 16:11 UTC, njooma requested changes

2024-05-16 17:38 UTC, njooma approved these changes

2024-05-16 17:42 UTC, stuqdog approved these changes
lgtm!

2024-05-16 17:47 UTC, merged