RSDK-3765: Flutter SDK Gantry API changes
viamrobotics/viam-flutter-sdk pull request #62
Opened 2023-07-06 22:45 UTC by martha-johnston

2023-07-06 23:17 UTC, njooma requested changes
Looking good! Just a few comments

2023-07-06 23:17 UTC, njooma commented on lib/src/components/gantry/gantry.dart
> +  /// Move the gantry to a new position at the requested speeds
Could you add the units here? Seems to be the only comment missing them

2023-07-06 23:17 UTC, njooma commented on test/unit_test/components/gantry_test.dart
> +      expect(gantry.positions, [2, 4, 6]);
Add another test here for checking speed

2023-07-06 23:28 UTC, clintpurser requested changes
Overall looks good, pointed out a few more spots i'd add checks for speed.

2023-07-06 23:28 UTC, clintpurser commented on test/unit_test/components/gantry_test.dart
>          expect(gantry.positions, [1, 2, 3]);
similar to above, add another check for speeds here.

2023-07-06 23:28 UTC, clintpurser commented on test/unit_test/components/gantry_test.dart
>          expect(gantry.positions, [1, 2, 3]);
also add check for speeds here

2023-07-06 23:28 UTC, clintpurser commented
Great job jumping into some dart @martha-johnston !!!

2023-07-07 15:08 UTC, benjirewis approved these changes
Nice! Great job on the dart 🎯 @martha-johnston (not that I know any dart lol); thank you!

2023-07-07 15:10 UTC, clintpurser approved these changes
LGTM

2023-07-07 15:18 UTC, njooma approved these changes

2023-07-07 15:19 UTC, merged